using System.Text;
using Microsoft.SemanticKernel;
using naija_shield_backend.Models;

namespace naija_shield_backend.Services;

/// <summary>
/// Uses Azure OpenAI via Semantic Kernel to convert a structured
/// <see cref="Report"/> (populated with statistics) into a full
/// prose regulatory document suitable for submission to CBN, NCC,
/// EFCC, NDPC, or internal stakeholders.
/// </summary>
public sealed class ReportNarrativeService
{
    private readonly Kernel _kernel;
    private readonly ILogger<ReportNarrativeService> _logger;

    public ReportNarrativeService(Kernel kernel, ILogger<ReportNarrativeService> logger)
    {
        _kernel = kernel;
        _logger = logger;
    }

    public async Task<string> GenerateAsync(Report report, CancellationToken cancellationToken = default)
    {
        var prompt = BuildPrompt(report);

        try
        {
            _logger.LogInformation(
                "[Narrative] Generating AI narrative for report Id={Id} agency={Agency}",
                report.Id, report.AgencyType);

            var result = await _kernel.InvokePromptAsync(prompt, cancellationToken: cancellationToken);
            var narrative = result.ToString().Trim();

            _logger.LogInformation(
                "[Narrative] Narrative generated. Length={Len} chars", narrative.Length);

            return narrative;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "[Narrative] LLM call failed for report Id={Id}", report.Id);
            return "Narrative generation failed. Please refer to the structured data fields in this report.";
        }
    }

    private static string BuildPrompt(Report report)
    {
        var s   = report.Summary;
        var sb  = new StringBuilder();

        // ── Classification breakdown as readable text ──────────────────────────
        var classLines = report.ByClassification
            .Select(c => $"    • {c.Classification}: {c.Count} incidents ({c.PercentOfTotal}% of total, avg risk score {c.AvgRiskScore}/100)")
            .ToList();

        var channelLines = report.ByChannel
            .Select(c => $"    • {c.Channel}: {c.Count} incidents ({c.Blocked} blocked)")
            .ToList();

        var stateLines = report.ByState
            .Take(5)
            .Select(s => $"    • {s.State}: {s.Count} incidents ({s.Blocked} blocked)")
            .ToList();

        sb.AppendLine($"""
            You are a senior cybersecurity analyst writing an official regulatory report for the NaijaShield platform.
            Write a formal, detailed, professional report using the statistics below. The report is addressed to: {report.AgencyType}.

            IMPORTANT RULES:
            - Use formal, regulatory language appropriate for a Nigerian financial/telecom regulator.
            - Do NOT invent numbers — use only the statistics provided.
            - Structure the report with clear numbered sections and headings.
            - Write in full, well-constructed paragraphs. No bullet points in the main body — prose only.
            - End with concrete, actionable recommendations for the agency.
            - The report should be comprehensive — aim for 600–900 words.

            ═══════════════════════════════════════════════
            REPORT STATISTICS (use these exactly)
            ═══════════════════════════════════════════════
            Report ID        : {report.Id}
            Agency           : {report.AgencyType}
            Reporting Period : {report.PeriodFrom} to {report.PeriodTo}
            Generated By     : {report.GeneratedBy}
            Framework        : {report.ComplianceMetadata.Framework}

            SUMMARY
            -------
            Total incidents analysed : {s.TotalIncidents}
            Blocked (high risk)      : {s.Blocked}
            Monitoring (elevated)    : {s.Monitoring}
            Allowed (low risk)       : {s.Allowed}
            Average risk score       : {s.AverageRiskScore}/100
            Total interventions      : {s.InterventionsTriggered}
            Unique source numbers    : {s.UniqueSourceNumbers}

            SCAM TYPOLOGY BREAKDOWN
            -----------------------
            {string.Join("\n", classLines)}

            CHANNEL BREAKDOWN
            -----------------
            {string.Join("\n", channelLines)}

            TOP AFFECTED STATES
            -------------------
            {(stateLines.Any() ? string.Join("\n", stateLines) : "    • Geographic data unavailable for this period")}

            ═══════════════════════════════════════════════
            Now write the full regulatory report below.
            Begin with: NAIJASHIELD THREAT INTELLIGENCE REPORT
            """);

        return sb.ToString();
    }
}
