using Newtonsoft.Json;

namespace naija_shield_backend.Models;

/// <summary>
/// Cosmos DB document that stores a generated regulatory report.
/// Partition key path: /agencyType (CBN | NCC | EFCC | NDPC | GENERAL).
/// </summary>
public sealed class Report
{
    [JsonProperty("id")]
    public string Id { get; set; } = default!;

    [JsonProperty("agencyType")]
    public string AgencyType { get; set; } = default!;      // partition key

    [JsonProperty("generatedAt")]
    public string GeneratedAt { get; set; } = default!;

    [JsonProperty("generatedBy")]
    public string GeneratedBy { get; set; } = default!;

    [JsonProperty("periodFrom")]
    public string PeriodFrom { get; set; } = default!;

    [JsonProperty("periodTo")]
    public string PeriodTo { get; set; } = default!;

    [JsonProperty("summary")]
    public ReportSummary Summary { get; set; } = default!;

    [JsonProperty("byClassification")]
    public List<ClassificationBreakdown> ByClassification { get; set; } = [];

    [JsonProperty("byChannel")]
    public List<ChannelBreakdown> ByChannel { get; set; } = [];

    [JsonProperty("byState")]
    public List<StateBreakdown> ByState { get; set; } = [];

    [JsonProperty("topIncidents")]
    public List<IncidentSummary> TopIncidents { get; set; } = [];

    [JsonProperty("complianceMetadata")]
    public ComplianceMetadata ComplianceMetadata { get; set; } = default!;

    /// <summary>
    /// Full AI-authored narrative report suitable for submission to a regulatory agency.
    /// Generated by GPT-4o-mini from the structured statistics above.
    /// </summary>
    [JsonProperty("narrative")]
    public string Narrative { get; set; } = string.Empty;
}

public sealed class ReportSummary
{
    [JsonProperty("totalIncidents")]
    public int TotalIncidents { get; set; }

    [JsonProperty("blocked")]
    public int Blocked { get; set; }

    [JsonProperty("monitoring")]
    public int Monitoring { get; set; }

    [JsonProperty("allowed")]
    public int Allowed { get; set; }

    [JsonProperty("averageRiskScore")]
    public int AverageRiskScore { get; set; }

    [JsonProperty("interventionsTriggered")]
    public int InterventionsTriggered { get; set; }

    [JsonProperty("uniqueSourceNumbers")]
    public int UniqueSourceNumbers { get; set; }
}

public sealed class ClassificationBreakdown
{
    [JsonProperty("classification")]
    public string Classification { get; set; } = default!;

    [JsonProperty("count")]
    public int Count { get; set; }

    [JsonProperty("percentOfTotal")]
    public double PercentOfTotal { get; set; }

    [JsonProperty("avgRiskScore")]
    public int AvgRiskScore { get; set; }
}

public sealed class ChannelBreakdown
{
    [JsonProperty("channel")]
    public string Channel { get; set; } = default!;

    [JsonProperty("count")]
    public int Count { get; set; }

    [JsonProperty("blocked")]
    public int Blocked { get; set; }
}

public sealed class StateBreakdown
{
    [JsonProperty("state")]
    public string State { get; set; } = default!;

    [JsonProperty("count")]
    public int Count { get; set; }

    [JsonProperty("blocked")]
    public int Blocked { get; set; }
}

public sealed class IncidentSummary
{
    [JsonProperty("id")]
    public string Id { get; set; } = default!;

    [JsonProperty("timestamp")]
    public string Timestamp { get; set; } = default!;

    [JsonProperty("channel")]
    public string Channel { get; set; } = default!;

    [JsonProperty("classification")]
    public string Classification { get; set; } = default!;

    [JsonProperty("riskScore")]
    public int RiskScore { get; set; }

    [JsonProperty("status")]
    public string Status { get; set; } = default!;

    [JsonProperty("state")]
    public string? State { get; set; }

    [JsonProperty("preview")]
    public string Preview { get; set; } = default!;
}

public sealed class ComplianceMetadata
{
    [JsonProperty("framework")]
    public string Framework { get; set; } = default!;

    [JsonProperty("dataProtection")]
    public string DataProtection { get; set; } = "Nigeria Data Protection Act (NDPA) 2023";

    [JsonProperty("reportVersion")]
    public string ReportVersion { get; set; } = "1.0";

    [JsonProperty("classification")]
    public string Classification { get; set; } = "CONFIDENTIAL";

    [JsonProperty("reportingEntity")]
    public string ReportingEntity { get; set; } = "NaijaShield Platform";
}
