using System.ComponentModel.DataAnnotations;

namespace naija_shield_backend.Models;

/// <summary>
/// JSON body expected by POST /api/ingest/voice.
/// Audio arrives as base64-encoded bytes so callers do not need
/// multipart form-data — a single JSON POST is sufficient.
/// </summary>
public class VoiceIngestRequest
{
    /// <summary>Unique identifier for this call leg, generated by the originating system.</summary>
    [Required]
    public string CallId { get; set; } = default!;

    /// <summary>Caller's MSISDN in international format, e.g. +2348055030371.</summary>
    [Required]
    public string From { get; set; } = default!;

    /// <summary>Called party's MSISDN or shortcode.</summary>
    [Required]
    public string To { get; set; } = default!;

    /// <summary>Base64-encoded audio bytes of the recorded call segment.</summary>
    [Required]
    public string AudioBase64 { get; set; } = default!;

    /// <summary>Container format of the audio: wav, mp3, or ogg.</summary>
    [Required]
    public string AudioFormat { get; set; } = "wav";

    /// <summary>ISO 8601 timestamp when the call was recorded.</summary>
    [Required]
    public string Timestamp { get; set; } = default!;
}
