using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;

namespace naija_shield_backend.Models;

/// <summary>
/// Multipart/form-data body expected by POST /api/ingest/voice.
/// </summary>
public class VoiceIngestRequest
{
    /// <summary>Unique identifier for this call leg, generated by the originating system.</summary>
    [Required]
    public string CallId { get; set; } = default!;

    /// <summary>Caller's MSISDN in international format, e.g. +2348055030371.</summary>
    [Required]
    public string From { get; set; } = default!;

    /// <summary>Called party's MSISDN or shortcode.</summary>
    [Required]
    public string To { get; set; } = default!;

    /// <summary>Raw audio file uploaded by the caller.</summary>
    [Required]
    public IFormFile AudioFile { get; set; } = default!;

    /// <summary>Container format of the audio: wav, mp3, or ogg.</summary>
    public string AudioFormat { get; set; } = "wav";

    /// <summary>ISO 8601 timestamp when the call was recorded.</summary>
    [Required]
    public string Timestamp { get; set; } = default!;
}
